language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - platform-tools
    - build-tools-24.0.0
    - android-24

script: ./gradlew clean check

sudo: false

before_cache: rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/