language: android
jdk: oraclejdk7

android:
  components:
    - android-24
    - build-tools-24.0.0

script: ./gradlew clean check

sudo: false

before_cache: rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/